#! /usr/bin/env python3
#-*- coding: UTF-8 -*-

### Legal
#
# Author:  Thomas DEBESSE <dev@illwieckz.net>
# License: ISC
# 

import argparse
import os
import subprocess
import configparser
import xdg.BaseDirectory
import distutils.spawn
from collections import OrderedDict

class ConfigFile():
	def __init__(self):
		self.parser = configparser.ConfigParser()
		self.modified = False

	def getKey(self, section, key):
		if not section in self.parser:
			return None

		if not key in self.parser[section]:
			return None

		return self.parser[section][key]

	def setKey(self, section, key, value):
		if not section in self.parser:
			self.parser.add_section(section)

		self.parser[section][key] = value
		self.modified = True

	def setDefaultFile(self, config_path):
		self.config_path = config_path

	def readDefault(self):
		self.readFile(self.config_path)

	def readFile(self, config_path):
		if os.path.isfile(config_path):
			print("reading config file: " + config_path)
			self.parser.read(config_path)

	def writeDefault(self):
		self.writeFile(self.config_path)

	def conditionalWriteDefault(self):
		if self.modified:
			self.writeDefault()
			self.modified = False

	def writeFile(self, config_path):
		with open(self.config_path, 'w') as configfile:
			print("writing config file: " + config_path)
			self.parser.write(configfile)

	def importConfig(self, config_file):
		for section in config_file.parser.sections():
			for key in config_file.parser[section]:
				self.setKey(section, key, config_file.getKey(section, key))

class XQEMURun():
	def __init__(self):
		self.config_base_dir_name = "xqemurun"
		self.config_base_file_name = "config.ini"
		self.config_path = os.path.join(xdg.BaseDirectory.xdg_config_home, self.config_base_dir_name, self.config_base_file_name)
		self.config_file = ConfigFile()
		self.config_runtime = ConfigFile()
		self.enabled_keyword_list = [ "enable", "enabled", "on", "yes" ]
		self.disabled_keyword_list = [ "disable", "disabled", "off", "no", "none" ]

	def getDefault(self, cat, key, default):
		value = self.config_runtime.getKey(cat, key)

		if value:
			return value
		else:
			return default

	def main(self):
		is_demo = os.environ.get("XQEMURUN_DEMO")

		if is_demo:
			self.config_path = '~/.config/xqemurun/config.ini'
		else:
			for xdg_config_dir_path in reversed(xdg.BaseDirectory.xdg_config_dirs):
				config_file_path = os.path.join(xdg_config_dir_path, self.config_base_dir_name, self.config_base_file_name)
				self.config_file.readFile(config_file_path)
				self.config_runtime.importConfig(self.config_file)

		default_options = {}
		default_options["config"] = self.config_path
		default_options["dir"] = self.getDefault("bin", "dir", "none")
		default_options["bin"]=self.getDefault("bin", "bin", "qemu-system-xbox")
		default_options["display"]=self.getDefault("sys", "display", "sdl")
		default_options["qemudebug"]=self.getDefault("sys", "qemudebug", "disabled")
		default_options["mesadebug"]=self.getDefault("sys", "mesadebug", "disabled")
		default_options["egldebug"]=self.getDefault("sys", "egldebug", "disabled")
		default_options["gldebug"]=self.getDefault("sys", "gldebug", "disabled")
		default_options["glsoftware"]=self.getDefault("sys", "glsoftware", "disabled")
		default_options["vsync"]=self.getDefault("sys", "vsync", "system")
		default_options["kvm"]=self.getDefault("core", "kvm", "disabled")
		default_options["xdk"]=self.getDefault("core", "xdk", "none")
		default_options["short"] = self.getDefault("core", "short", "disabled")
		default_options["machine"] = self.getDefault("core", "machine", "xbox")
		default_options["bootrom"] = self.getDefault(default_options["machine"], "bootrom", "none")
		default_options["bios"] = self.getDefault(default_options["machine"], "bios", "none")
		default_options["disk"] = self.getDefault(default_options["machine"], "disk", "none")
		default_options["hub"] = self.getDefault("usb", "hub", "emulated")
		default_options["pad1"] = self.getDefault("usb", "pad1", "keyboard")
		default_options["pad2"] = self.getDefault("usb", "pad2", "disabled")
		default_options["pad3"] = self.getDefault("usb", "pad3", "disabled")
		default_options["pad4"] = self.getDefault("usb", "pad4", "disabled")
		default_options["media"] = self.getDefault(default_options["machine"], "media", "none")

		args = argparse.ArgumentParser(description="%(prog)s helps to run xqemu easily.")
		args.add_argument("--config", dest="config", metavar="FILE", help="path to config file, default: %(default)s", default=default_options["config"])
		args.add_argument("--dir", dest="dir", metavar="DIRECTORY", help="directory from where to run XQEMU binary, default: %(default)s", default=default_options["dir"])
		args.add_argument("--bin", dest="bin", metavar="FILE", help="XQEMU binary, default: %(default)s", default=default_options["bin"])
		args.add_argument("--display", dest="display", metavar="DISPLAY", help="graphical display, default: %(default)s", default=default_options["display"])
		args.add_argument("--qemudebug", dest="qemudebug", metavar="OPTION", help="QEMU debug mode, default: %(default)s", default=default_options["qemudebug"])
		args.add_argument("--mesadebug", dest="mesadebug", metavar="OPTION", help="Mesa debug info printing, default: %(default)s", default=default_options["mesadebug"])
		args.add_argument("--egldebug", dest="egldebug", metavar="OPTION", help="EGL debug info printing, default: %(default)s", default=default_options["egldebug"])
		args.add_argument("--gldebug", dest="gldebug", metavar="OPTION", help="OpenGL debug info printing, default: %(default)s", default=default_options["gldebug"])
		args.add_argument("--glsoftware", dest="glsoftware", metavar="DRIVER", help="OpenGL software rendering, default: %(default)s", default=default_options["glsoftware"])
		args.add_argument("--vsync", dest="vsync", metavar="OPTION", help="Vertical sync mode, default: %(default)s", default=default_options["vsync"])
		args.add_argument("--kvm", dest="kvm", metavar="OPTION", help="enable KVM acceleration, default: %(default)s", default=default_options["kvm"])
		args.add_argument("--xdk", dest="xdk", metavar="SOCKET", help="path to socket file for XDK serial port, default: %(default)s", default=default_options["xdk"])
		args.add_argument("--short", dest="short", metavar="OPTION", help="skip the logo animation, default: %(default)s", default=default_options["short"])
		args.add_argument("--machine", dest="machine", metavar="OPTION", help="machine type, default: %(default)s", default=default_options["machine"])
		args.add_argument("--bootrom", dest="bootrom", metavar="FILE", help="path to bootrom dump, default: %(default)s", default=default_options["bootrom"])
		args.add_argument("--bios", dest="bios", metavar="FILE", help="path to bios dump, default: %(default)s", default=default_options["bios"])
		args.add_argument("--disk", dest="disk", metavar="FILE", help="path to disk image, default: %(default)s", default=default_options["disk"])
		args.add_argument("--hub", dest="hub", metavar="OPTION", help="usb hub option, default: %(default)s", default=default_options["hub"])
		args.add_argument("--pad1", dest="pad1", metavar="OPTION", help="usb pad1 device option, default: %(default)s", default=default_options["pad1"])
		args.add_argument("--pad2", dest="pad2", metavar="OPTION", help="usb pad2 device option, default: %(default)s", default=default_options["pad2"])
		args.add_argument("--pad3", dest="pad3", metavar="OPTION", help="usb pad3 device option, default: %(default)s", default=default_options["pad3"])
		args.add_argument("--pad4", dest="pad4", metavar="OPTION", help="usb pad4 device option, default: %(default)s", default=default_options["pad4"])
		args.add_argument("media", nargs='?', metavar="FILE", help="path to media iso, default: %(default)s", default=default_options["media"])

		args = args.parse_args()

		if is_demo:
			return

		if args.config:
			self.config_path = os.path.abspath(args.config)

		self.config_file.setDefaultFile(self.config_path)

		print("config file: " + self.config_path)
		if os.path.isfile(self.config_path):
			self.config_file.readDefault()
			self.config_runtime.importConfig(self.config_file)
		else:
			print("config file not there")

		if args.dir in self.disabled_keyword_list:
			self.config_runtime.setKey("bin", "dir", "none")
		else:
			self.config_runtime.setKey("bin", "dir", os.path.abspath(args.dir))

		if distutils.spawn.find_executable(args.bin):
			self.config_runtime.setKey("bin", "bin", args.bin)
		elif os.path.exists(args.bin):
			# security breach? it silently uses the file in current directory if not in $PATH but in current directory
			self.config_runtime.setKey("bin", "bin", os.path.abspath(args.bin))

		if args.kvm in self.disabled_keyword_list:
			self.config_runtime.setKey("core", "kvm", "disabled")
		else:
			self.config_runtime.setKey("core", "kvm", "enabled")

		if args.xdk in self.disabled_keyword_list:
			self.config_runtime.setKey("core", "xdk", "none")
		else:
			self.config_runtime.setKey("core", "xdk", os.path.abspath(args.xdk))

		self.config_runtime.setKey("core", "machine", args.machine)
		machine = args.machine

		if args.qemudebug in self.disabled_keyword_list:
			self.config_runtime.setKey("sys", "qemudebug", "disabled")
		else:
			self.config_runtime.setKey("sys", "qemudebug", "enabled")

		self.config_runtime.setKey("sys", "display", args.display)

		self.config_runtime.setKey("sys", "mesadebug", args.mesadebug)

		self.config_runtime.setKey("sys", "egldebug", args.egldebug)

		self.config_runtime.setKey("sys", "gldebug", args.gldebug)

		self.config_runtime.setKey("sys", "glsoftware", args.glsoftware)

		self.config_runtime.setKey("sys", "vsync", args.vsync)

		if args.short in self.disabled_keyword_list:
			self.config_runtime.setKey("core", "short", "no")
		else:
			self.config_runtime.setKey("core", "short", "yes")

		self.config_runtime.setKey(machine, "bootrom", os.path.abspath(args.bootrom))

		self.config_runtime.setKey(machine, "bios", os.path.abspath(args.bios))

		if args.disk in self.disabled_keyword_list:
			self.config_runtime.setKey(machine, "disk", "none")
		else:
			self.config_runtime.setKey(machine, "disk", os.path.abspath(args.disk))

		if args.media in self.disabled_keyword_list:
			self.config_runtime.setKey(machine, "media", "none")
		else:
			self.config_runtime.setKey(machine, "media", os.path.abspath(args.media))

		self.config_runtime.setKey("usb", "hub", args.hub)

		self.config_runtime.setKey("usb", "pad1", args.pad1)

		self.config_runtime.setKey("usb", "pad2", args.pad2)

		self.config_runtime.setKey("usb", "pad3", args.pad3)

		self.config_runtime.setKey("usb", "pad4", args.pad4)

		self.cli()

	# not yet used
	def config(self):
		alteredConfig = False

		machine = self.config_runtime.getKey("core", "machine")

		if not machine:
			machine = input("machine [xbox]:")

			if machine == "":
				machine = "xbox"

			if machine not in [ "xbox", "chihiro" ]:
				raise(Exception("UnknownMachine"))

			self.config_runtime.setKey("core", "machine", machine)
			self.config_file.setKey("core", "machine", machine)

		if not self.config_runtime.getKey("bin", "bin"):
			bin_path = input("path to qemu: ") 
			self.config_runtime.setKey("bin", "bin", bin_path)
			self.config_file.setKey("bin", "bin", bin_path)

		if not self.config_runtime.getKey(machine, "bootrom"):
			bootrom_path = input("path to bootrom dump: ")
			self.config_runtime.setKey(machine, "bootrom", bootrom_path)
			self.config_file.setKey(machine, "bootrom", bootrom_path)

		if not self.config_runtime.getKey(machine, "bios"):
			bios_path = input("path to bios dump: ")
			self.config_runtime.setKey(machine, "bios", bios_path)
			self.config_file.setKey(machine, "bios", bios_path)

		self.config_file.conditionalWriteDefault()

	def cli(self):
		self.qemu()

	def qemu(self):
		mesadebug = self.config_runtime.getKey("sys", "mesadebug") 
		if mesadebug in self.enabled_keyword_list:
			print("mesa debug: enabled")
			os.environ["MESA_DEBUG"] = "1"
		elif mesadebug in self.enabled_keyword_list:
			print("mesa debug: enabled")
			os.environ["MESA_DEBUG"] = ""
		elif mesadebug == "system":
			print("mesa debug: system")
		else:
			print("mesa debug: enabled with flags" + mesadebug)
			os.environ["MESA_DEBUG"] = "1," + mesadebug

		egldebug = self.config_runtime.getKey("sys", "egldebug") 
		if egldebug in self.enabled_keyword_list:
			print("egl debug: enabled")
			os.environ["EGL_LOG_LEVEL"] = "debug"
		elif egldebug in self.enabled_keyword_list:
			print("egl debug: enabled")
			os.environ["EGL_LOG_LEVEL"] = ""
		elif egldebug == "system":
			print("egl debug: system")
		else:
			print("egl debug: " + egldebug)
			os.environ["EGL_LOG_LEVEL"] = egldebug

		glsoftware = self.config_runtime.getKey("sys", "glsoftware")
		if glsoftware not in self.disabled_keyword_list:
			print("gl software: enabled")
			os.environ["LIBGL_ALWAYS_SOFTWARE"] = "1"

			if glsoftware not in self.enabled_keyword_list:
				print("gl software driver: " + glsoftware)
				os.environ["GALLIUM_DRIVER"] = glsoftware

		vsync = self.config_runtime.getKey("sys", "vsync")
		if vsync in self.enabled_keyword_list:
			print("vsync: enabled")
			os.environ["vblank_mode"] = "3"
		elif vsync in self.disabled_keyword_list:
			print("vsync: disabled")
			os.environ["vblank_mode"] = "0"
		elif vsync == "system":
			print("vsync: system")
		else:
			print("vsync: vblank mode " + vsync)
			os.environ["vblank_mode"] = vsync

		qemu_command = []
		qemu_options = []

		qemu_dir_path = self.config_runtime.getKey("bin", "dir")

		machine = self.config_runtime.getKey("core", "machine")
		print("machine type: " + machine)

		print("qemu execution directory: " + qemu_dir_path)

		qemu_bin_path = self.config_runtime.getKey("bin", "bin")
		print("qemu path: " + qemu_bin_path)

		qemu_command += [ qemu_bin_path ]

		if self.config_runtime.getKey("sys", "qemudebug") in self.enabled_keyword_list:
			print("qemu debug: enabled")
			qemu_options += [ "-s", "-S" ]
		else:
			print("qemu debug: disabled")

		qemu_display = self.config_runtime.getKey("sys", "display")
		print("display: " + qemu_display)
		qemu_options += [ "-display", qemu_display ]

		if self.config_runtime.getKey("core", "kvm") in self.enabled_keyword_list:
			print("kvm: enabled")
			kvm_enabled = True
		else:
			print("kvm: disabled")
			kvm_enabled = False

		xdk_socket = self.config_runtime.getKey("core", "xdk")
		if xdk_socket and xdk_socket in self.enabled_keyword_list:
			print("xdk: " + xdk_socket)
		else:
			print("xdk: disabled")
			xdk_socket = None

		qemu_cpu_arg="pentium3"
		qemu_options += [ "-cpu", qemu_cpu_arg ]

		qemu_machine_arg = machine

		if machine == "chihiro":
			print("memory: 128Mb")
			qemu_memory_arg="128"
			mediaboard_path = self.config_runtime.getKey(machine, "bootrom")
			print("mediaboard dump: " + mediaboard_path)
			qemu_machine_arg += ",mediaboard_rom=" + mediaboard_path

		else:
			print("memory: 64Mb")
			qemu_memory_arg="64"
			bootrom_path = self.config_runtime.getKey(machine, "bootrom")
			print("bootrom dump: " + bootrom_path)
			qemu_machine_arg += ",bootrom=" + bootrom_path

		qemu_options += [ "-m", qemu_memory_arg ]

		if xdk_socket:
			qemu_xdk_socket_arg = "unix:" + xdk_socket
			qemu_options += [ "-device", "lpc47m157", "-serial", qemu_xdk_socket_arg ]

		if kvm_enabled:
			qemu_machine_arg += ",accel=kvm,kernel_irqchip=off"

		if self.config_runtime.getKey("core", "short") in self.enabled_keyword_list:
			print("skip logo animation: yes")
			qemu_machine_arg += ",short_animation"
		else:
			print("skip logo animation: no")

		qemu_options += [ "-machine", qemu_machine_arg ]

		bios_path = self.config_runtime.getKey(machine, "bios")
		print("bios dump: " + bios_path)
		qemu_bios_arg = bios_path
		qemu_options += [ "-bios", qemu_bios_arg ]

		if machine == "xbox":
			qemu_disk_arg = "index=0,media=disk,locked=on"
			disk_path = self.config_runtime.getKey(machine, "disk")

			if disk_path and disk_path not in self.disabled_keyword_list:
				print("disk image: " + disk_path)
				qemu_disk_arg += ",file=" + disk_path
			else:
				print("disk image: none")
				qemu_disk_arg += ",file=/dev/zero"

			qemu_options += [ "-drive", qemu_disk_arg ]

		qemu_media_arg = "index=1,media=cdrom"

		media_path = self.config_runtime.getKey(machine, "media")
		if media_path and media_path not in self.disabled_keyword_list:
			print("media iso: " + media_path)
			qemu_media_arg += ",file=" + media_path
		else:
			print("media iso: none")

		qemu_options +=	[ "-drive", qemu_media_arg ]

		pad_dict = OrderedDict()
		pad_dict["pad1"] = "3"
		pad_dict["pad2"] = "4"
		pad_dict["pad3"] = "1"
		pad_dict["pad4"] = "2"

		usb_hub_option = self.config_runtime.getKey("usb", "hub")
		if not usb_hub_option:
			usb_hub_option = "emulated"

		if usb_hub_option == "emulated":
			print("usb hub: emulated")
			qemu_usb_hub_device_arg = "usb-hub,bus=usb-bus.0,port=3"
			qemu_options += [ "-usb", "-device", qemu_usb_hub_device_arg ]

		elif usb_hub_option[0:8] == "forward:":
			print("usb hub: " + usb_hub_option)
			usb_product_id = usb_hub_option[8:13]
			usb_vendor_id = usb_hub_option[14:19]
			qemu_usb_hub_device_arg = "usb-host,bus=usb-bus.0,port=3,productid=" + usb_product_id + ",vendorid=" + usb_vendor_id
			qemu_options += [ "-usb", "-device", qemu_usb_hub_device_arg ]

		if usb_hub_option == "emulated":
			for pad in pad_dict.keys():
				usb_pad_option = self.config_runtime.getKey("usb", "usb_" + pad)
				if not usb_pad_option:
					if pad == "pad1":
						usb_pad_option = "keyboard"
					else:
						usb_pad_option = "disabled"

				if usb_pad_option == "keyboard":
					print("usb " + pad + ": keyboard")
					qemu_usb_pad_device_arg = "usb-xbox-gamepad,bus=usb-bus.0,port=" + pad_dict[pad] + ".2"
					qemu_options += [ "-device", qemu_usb_pad_device_arg ]

				elif usb_pad_option[0:8] == "forward:":
					print("usb " + pad + ": " + usb_pad_option)
					usb_product_id = usb_hub_option[8:13]
					usb_vendor_id = usb_hub_option[14:19]
					qemu_usb_pad_device_arg = "usb-host,bus=usb-bus.0,port=3.2,productid=" + usb_product_id + ",vendorid=" + usb_vendor_id
					qemu_options += [ "-usb", "-device", qemu_usb_hub_device_arg ]

		final_command = qemu_command + qemu_options

		print("qemu command line : " + str(final_command))

		if qemu_dir_path not in self.disabled_keyword_list:
			os.chdir(qemu_dir_path)

		subprocess.call(final_command)

if __name__ == "__main__":
	xqemurun = XQEMURun()
	xqemurun.main()
